### ISSUE TITLE
Error previewing an elasticsearch layer on openlayers

### ISSUE THREAD

**Issue by dersteppenwolf** [ngageoint/elasticgeo#43] opened 2017-05-31 00:22 UTC
looks like there is some kind of error creating a point layer from elasticsearch

> 2017-05-30 19:17:41,561 WARN [wms.map] - Failed to determine CRS axis order, assuming is EN
> org.opengis.referencing.NoSuchAuthorityCodeException: No code "CRS:GC,DEF,CRS,EPSG,4326" from authority "Web Map Service CRS" found for object of type "CoordinateReferenceSystem".
> ...
> Caused by: java.lang.NumberFormatException: For input string: "GC,DEF,CRS,EPSG,4326"
> 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> 	at java.lang.Integer.parseInt(Integer.java:580)
> 	at java.lang.Integer.parseInt(Integer.java:615)

geoserver 2.11.1
tomcat apache-tomcat-8.5.14
java 1.8.0_111
elasticsearch 5.4.0
elasticgeo 2.11.0

**Comment by sjudeng** [comment] 2017-05-31 01:31
I think it's a GeoServer issue. I can reproduce the message using GeoServer 2.11.1 without the plugin installed using one of the demo layers (`sf:bugsites`). Does the layer still appear to display properly?

**Comment by sjudeng** [comment] 2017-08-19 00:20
It looks like this issue is resolved in GeoServer 2.11.2.

**Closed by sjudeng** 2017-08-19 00:20 UTC
