### ISSUE TITLE
aggregation - not all tiles are getting returned with the same scaling

### ISSUE THREAD

**Issue by nreese** [ngageoint/elasticgeo#26] opened 2017-03-29 19:10 UTC
I am running ElasticSearch 5.1.2 with an index containing all earthquakes [recorded by USGS](https://earthquake.usgs.gov/fdsnws/event/1/) since 2013.

When zooming, not all of the returned tiles contain the same resolution.  

![tilesnotsameresolution](https://cloud.githubusercontent.com/assets/373691/24471865/bb3c461c-1480-11e7-8c85-2e4a96030cee.gif)

**Comment by sjudeng** [comment] 2017-03-29 20:33
Do the problematic tiles always cross the dateline or do you see it elsewhere as well? Precision is computed based on envelope size in degrees (see [GeohashUtil.java#L23-L24](https://github.com/ngageoint/elasticgeo/blob/68109c633075a675e8b6db5337952c9a22e366e9/gt-elasticsearch-parent/gt-elasticsearch-core/src/main/java/mil/nga/giat/data/elasticsearch/GeohashUtil.java#L23-L24)) so I suspect an update will be needed to handle case when tile crosses the dateline.

**Comment by nreese** [comment] 2017-03-30 19:42
I found one case that does not involve the dateline

![blocky](https://cloud.githubusercontent.com/assets/373691/24522978/ac29c7de-154e-11e7-87f3-afeb988b9056.gif)

**Comment by sjudeng** [comment] 2017-03-30 19:52
I'm wondering if this one could be an artifact of which tiles are being re-requested (and when) by the client. Maybe tips in [this post](http://stackoverflow.com/questions/15048096/how-do-i-force-a-leaflet-map-to-reload-all-tiles-including-visible-ones) or similar will help.

**Comment by GISDev01** [comment] 2017-04-21 22:09
@nreese Can you take a capture of the network traffic in the browser as you experience this issue? That capture should indicate if a new tile request for that location is really being requested by the browser and sent back at the wrong spatial resolution.

**Comment by nreese** [comment] 2017-04-24 19:20
The tile returned for the request http://localhost:8080/geoserver/elastic/wms?SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=elastic%3Aevent&STYLES=earthquake&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&VIEWPARAMS=a%3A%7B%22aggs%22%3A%20%7B%22geohash_grid%22%3A%20%7B%22field%22%3A%20%22location%22%7D%5C%2C%22aggs%22%3A%20%7B%22metric%22%3A%20%7B%22max%22%3A%20%7B%22field%22%3A%20%22magnitude%22%7D%7D%7D%7D%7D&SRS=EPSG%3A3857&BBOX=-7514065.628545966,-7.081154551613622e-10,-5009377.085697311,2504688.5428486555 looks a little weird. It looks like some pixels are bigger than others. But, when you blow the tile up, the blockiness may just be an artifact of the data - having a very dense set of data that looks blocky.

![image](https://cloud.githubusercontent.com/assets/373691/25354444/3a58ea26-28f0-11e7-8b0c-14827306b72a.png)

![image](https://cloud.githubusercontent.com/assets/373691/25354562/95ef409c-28f0-11e7-826e-bb53e9ef2e74.png)

**Comment by sjudeng** [comment] 2017-04-26 16:11
@nreese, @GISDev01 Thanks for looking at this. The issue at the dateline is clearly a plugin bug. I'll at least take a look at that as soon as I can. But please report back if you find more evidence the issue is broader.

**Comment by sjudeng** [comment] 2017-05-10 22:11
Just merged #38 which should resolve this. Please reopen if you still observe the issue.

**Closed** 2017-05-10 22:10 UTC
